name: Run KMC naya automate Notebook Daily

# Run the workflow on a schedule
on:
  schedule:
    - cron: '15 10 * * *'  # Runs at 10:15 AM UTC, which is 4:00 PM Nepali Time daily.
  workflow_dispatch:       # Allows you to manually trigger the workflow if needed.

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install Jupyter and nbconvert
        run: |
          pip install jupyter nbconvert
          # Add any other dependencies here, if needed.

      # Step 4: Execute the notebook
      - name: Run the notebook
        run: |
          jupyter nbconvert --to notebook --execute --inplace "KMC_naya_automate.ipynb"
      
      # Optional: Upload notebook output
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact


      
      
