name: NEPSE Quantum Analysis

on:
  schedule:
    - cron: '15 10 * * 0-4'  # 4 PM NPT Sun-Thu
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Kathmandu
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install pandas numpy xgboost scipy requests
      
    - name: Run Analysis
      env:
        GH_TOKEN: ${{ secrets.QUANTUM_PAT }}
      run: python New_nepse.py
