name: Run KMC naya automate Notebook Daily

on:
  workflow_dispatch:  # Allows manual runs
  schedule:
    - cron: '15 10 * * *'  # Runs daily at 10:15 AM UTC

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install jupyter nbconvert gitpython

      - name: Clone Nepse Repository
        run: |
          python clone_repo.py

      - name: Run the notebook
        run: |
          jupyter nbconvert --to notebook --execute --inplace "KMC_naya_automate.ipynb"
