name: NEPSE Daily Automation

on:
  schedule:
    - cron: '15 10 * * 0-4'  # 4 PM Nepal Time (10:15 UTC) Sunday-Thursday
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Kathmandu  # Nepal timezone

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests gitpython python-dotenv

      - name: Run automation script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python nepse_automation.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update data [Manual Trigger]"
          git push
