name: NEPSE Daily Automation

on:
  schedule:
    - cron: '15 10 * * 0-4'  # 4 PM Nepal Time (10:15 UTC), Sun-Thu
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Kathmandu
      GITHUB_WORKSPACE: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests gitpython python-dotenv \
              nepse-scraper xlsxwriter beautifulsoup4 joblib \
              scikit-learn matplotlib

      - name: Run automation script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          mkdir -p data
          python nepse_automation.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Add only relevant files
          git add *.csv
          
          # Smart commit handling
          git diff-index --quiet HEAD || git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M:%S')"
          
          # Secure push
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}
          git push origin HEAD:main

      - name: Cleanup old files
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Keep last 3 files of each type
          for prefix in espen EMA_Cross_for; do
            files=$(git ls-files -- "$prefix*.csv" | sort -r | awk 'NR>3')
            [ -n "$files" ] && git rm -q $files
          done
          
          # Commit and push cleanup
          git diff-index --quiet HEAD || git commit -m "Auto-cleanup old files"
          git push origin HEAD:main
