name: NEPSE Daily Automation

on:
  schedule:
    # Runs at 4 PM Nepal Time (UTC+5:45) every Sunday-Thursday
    - cron: '15 10 * * 0-4'  # 10:15 UTC = 16:00 Nepal Time

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Kathmandu  # Set timezone to Nepal

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests gitpython python-dotenv

      - name: Run automation script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the secret token
        run: |
          python nepse_automation.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update data"
          git push
