name: Nepse Data Updater

on:
  schedule:
    - cron: '0 20 * * *'  # 8 PM UTC (2:15 AM NPT)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # - name: Install dependencies
    #   run: pip install -r requirements.txt

    - name: Run data updater
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python main.py
